awk -f calcOPchanges.awk ../Data/POPC/CaCl/SLIPID/OPvsCACLconsALLSCALED.dat  > ../Data/POPC/CaCl/SLIPID/SLIPIDcaclCONSchangeALLSCALED.dat 
awk -f calcOPchanges.awk ../Data/POPC/CaCl/SLIPID/OPvsCACLconsHGSCALED.dat  > ../Data/POPC/CaCl/SLIPID/SLIPIDcaclCONSchangeHGSCALED.dat 
awk -f calcOPchanges.awk ../Data/POPC/CaCl/SLIPID/OPvsCACLconsHGglycSCALED.dat  > ../Data/POPC/CaCl/SLIPID/SLIPIDcaclCONSchangeHGglycSCALED.dat 
awk -f calcOPchanges.awk ../Data/POPC/CaCl/SLIPID/OPvsCACLconsHGglycSCALED_0.85.dat  > ../Data/POPC/CaCl/SLIPID/SLIPIDcaclCONSchangeHGglycSCALED_0.85.dat 
awk -f calcOPchanges.awk ../Data/POPC/CaCl/lipid14/OPvsCACLconsORIG.dat  > ../Data/POPC/CaCl/lipid14/LIPID14caclCONSchangeORIG.dat 
awk -f calcOPchanges.awk ../Data/POPC/CaCl/lipid14/OPvsCACLconsHGSCALED.dat  > ../Data/POPC/CaCl/lipid14/LIPID14caclCONSchangeHGSCALED.dat 
awk -f calcOPchanges.awk ../Data/POPC/NaCl/Slipids-VIS/OPvsNACLconsALLSCALED.dat  > ../Data/POPC/NaCl/Slipids-VIS/SLIPIDnaclCONSchangeALLSCALED.dat 
awk -f calcOPchanges.awk ../Data/POPC/NaCl/Slipids-VIS/OPvsNACLconsHGSCALED.dat  > ../Data/POPC/NaCl/Slipids-VIS/SLIPIDnaclCONSchangeHGSCALED.dat 
awk -f calcOPchanges.awk ../Data/POPC/NaCl/Slipids-VIS/OPvsNACLconsHGglycSCALED.dat  > ../Data/POPC/NaCl/Slipids-VIS/SLIPIDnaclCONSchangeHGglycSCALED.dat 
awk -f calcOPchanges.awk ../Data/POPC/NaCl/Slipids-VIS/OPvsNACLconsHGglycSCALED_0.85.dat  > ../Data/POPC/NaCl/Slipids-VIS/SLIPIDnaclCONSchangeHGglycSCALED_0.85.dat 
awk -f calcOPchanges.awk ../Data/POPC/NaCl/lipid14/OPvsNACLconsHGSCALED.dat  > ../Data/POPC/NaCl/lipid14/LIPID14naclCONSchangeHGSCALED.dat 
awk -f calcOPchanges.awk ../Data/POPC/NaCl/lipid14/OPvsNACLconsORIG.dat  > ../Data/POPC/NaCl/lipid14/LIPID14naclCONSchangeORIG.dat 
